### ISSUE TITLE
Equipping items to body and chest not working

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#100]

**Comment by MoreOutput** [comment]
There are currently no chest/body items -- have you created one? Can you post the object?

**Comment by wizardsambolton** [comment]
Yeah I have created one, and have it in a merchant store, here is the item:

```
{
						name: 'Leather Chestplate',
						short: 'a leather chestplate',
						long: 'A simple leather chestplate was left here' ,
						area: 'Incipio',
						id: '10003',
						level: 1,
						itemType: 'armor',
						material: 'leather',
						ac: 3,
						weight: 1,
						slot: 'body',
						equipped: false,
						store:true,
						worth:15,
						spawn:5,
						flags: []
					}
```

**Comment by MoreOutput** [comment]
Thanks! Looking after work today.

**Comment by wizardsambolton** [comment]
Awesome thanks!

**Comment by MoreOutput** [comment]
I'm having trouble replicating this. Working as intended. May be due to some work i've done on my end. Keeping this open until I push to master -- once that happens I'll close but please retest. Will add some body armor to the game.

Note: with this push  the 'worth' property is now 'value' which was the original intention (why worth was not outlined on item.json).

**Comment by wizardsambolton** [comment]
Awesome thanks!

**Comment by MoreOutput** [comment]
Next couple days; wrapped into some work im doing.

**Comment by wizardsambolton** [comment]
Cool!

**Comment by MoreOutput** [comment]
A chest piece was added to master with the weekends commit.
