### ISSUE TITLE
Command to view gold balance 

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#96]

**Comment by MoreOutput** [comment]
currently on 'score' will add a 'worth' command which is typically found in dikus.

**Comment by wizardsambolton** [comment]
Awesome ty!

**Comment by wizardsambolton** [comment]
Also say I wanted to change the name of gold, is there any quick way of going about that?

**Comment by MoreOutput** [comment]
Worth (wo) was added. Will send you a simple one-liner with a players current gold. 

There were, with the new worth command, only two references to the word 'gold' -- in commands.js. 

After some thought -- I added a new property to config.js: 'coinage'. Changing this value will change the display name everywhere. Because of this the end of comabat string in Combat.js was adjusted to give this value upon mob death. Previously it gave 'coints'.

The default value of World.config.coinage is 'gold'.
