### ISSUE TITLE
Practice <Spell> command returning no output

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#98]

**Comment by MoreOutput** [comment]
Looking at this. Its related to the dev im doing for this iteration actually. Expected behavior.

To clarify a bit on the skill system: A trainer must have the skill you want to train. The trainers skill must meet certain criteria (be better than the players). In addition to this skills can have prerequisites (level, a stat, another skill). To make a game entity a 'trainer' its trainer property should be toggled to true.

You can adjust this stuff in commands.js in the practice function.

**Comment by wizardsambolton** [comment]
Sorry to bother you, however what do I need to change to re enable the practice command?
